### ISSUE TITLE
Filter replaced by album title when it shouldn't be

### ISSUE THREAD

**Issue by frogworth** [ghDaYuYu/foo_discogs#28]
In the Find Release dialog, every time you adjust anything - e.g. you're searching for Boris, and you need to click through Boris (1), Boris (3) etc to find the right one - the Filter is replaced by whatever's tagged in the album title.

This can be inconvenient. If it's a CD with no tags, or untagged files, the filter keeps getting erased and you need to retype it. If the album title has punctuation in it, you might want to filter on a fragment of the title, and you have to keep editing that each time.

Can you possible change it to the old behaviour, where the Filter is initialised with album title, but then whatever you type in there stays for as long as the dialog is open?
Thanks!

**Comment by ghDaYuYu** [comment]
Changed the code so that the filter stays unchanged while clicking through different artists, although
made the exception that if empty, will be filled with the current Album when found in the current results.
I´m not very happy also about how the release selections work at the moment, can be confusing and error prone.
Much better now, a bit closer to the old behaviour...
Regards!

**Comment by frogworth** [comment]
Sounds awesome! I look forward to testing in the next release.
Thanks so much for your responsiveness and thoughtfulness.

**Comment by ghDaYuYu** [comment]
Fixed in v2.23-mod.18.2
