### ISSUE TITLE
TRACKNUMBER is not getting written to

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#3]
I'm trying to write tags from this URL https://www.discogs.com/Chicane-Featuring-Maire-Brennan-Of-Clannad-Saltwater/release/416201 to the TRACKNUMBER field but it's not written that to it.

Here's my mapping for it.
![image](https://user-images.githubusercontent.com/14054664/107126780-cc394880-68a9-11eb-8154-5dc5d376bf92.png)

**Comment by stephen147** [comment]
A lot of other tags have this issue, so I had to revert to the original plugin.

**Comment by ghDaYuYu** [comment]
Hi stephen147,

I can not replicate this issue... I've just tested TRACKNUMBER write+update (three generic mp3s on my drive with provided discogs Chicane release) and all files were tagged with their corresponding track #

The only difference I can think of right now, related to tags update, between this mod and the original plugin, is that release id, master release id, artist id and label id (the four greyed out 'write' only tags) need to be deleted manually in order to rewrite them.

I would try to export the tag mapping to test with defaults, but I am not sure if this may help tracing this issue.

**Comment by stephen147** [comment]
Thanks for getting back, I've noticed you've updated this since.

Is there a download for the `fb2k-component` file? I'm not sure how to pack the code. I've read the info but don't know how to go about that so that I can try this again.

Thanks.

**Comment by ghDaYuYu** [comment]
Yes, code has been added to deal with tags containing carriage returns. I am considering to include this change together with an update for the track matching panel in next release.
But please bear with me though, if the current release might be arbitrarily failing to write tags, that should take preference over any further component releases.
Are you 100% confident that you have tested both this and the original component using the same settings and test data?
If yes, would you please provide a download link with (both from the original and modded versions) exported tag mapping and .cfg files so I can reproduce the same scenario here?

**Comment by stephen147** [comment]
It appears it works again after the latest update. Thanks.
