### ISSUE TITLE
Submit this version to the foobar repository

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#30]
Is it possible to submit this version to the foobar repository to have auto-updates?

**Comment by ghDaYuYu** [comment]
That would be great... unfortunately I believe it would be a tad confusing... not everybody has your well-tempered patience dealing with the amount of crashes, bugs, etc. included in these releases : ) 
Hopefully in a month or so we will have a much more stable plugin.
Cheers!

**Comment by stephen147** [comment]
I think it's great. The only big bug for me is the one with the [hidden tracks](https://github.com/ghDaYuYu/foo_discogs/issues/27) but that's it. The rest are minor ;)

**Comment by ghDaYuYu** [comment]
Although there´s still the issue... the ui hangs while building the tree for long release lists. Hopefully will get fixed soon.

**Comment by gitgetgot** [comment]
@ghuDaYuYu 
 
> That would be great... unfortunately I believe it would be a tad confusing... not everybody has your well-tempered patience dealing with the amount of crashes, bugs, etc. included in these releases : )

If it is possible, you could add the modded plugin as BETA (or a successor?) in the repository? It has a _new name_! so it is not the same component and ppl. won't f#*k up their working fb2ks accidentially...

The old component would still be available (because maybe zoomorph will do some kind of hotfixes, IF discogs-api will be changed or something), and ppl. eager to test this modded version can autoupdate easily. With or without crashes ;-]

Just my 2 cents...

**Comment by ghuDaYuYu** [comment]
Extension to the hidden tracks functionality is on the works, problem as usual is finding the time to test new features, cleaning up code... About the foobar repository, I am closing the issue for now as non-issue, maybe it should be moved to the discussion area someday, idk
