### ISSUE TITLE
Filter is overwritten with old value, although the user has removed all filter text.

### ISSUE THREAD

**Issue by gitgetgot** [ghDaYuYu/foo_discogs#50]
Version: 1.0.4
Compiled: Aug 19 2021

I start the modded component on an album, so the filter is autofilled with the album name. (thats fine!)

When I delete the filter and change the artist, the filter-text is autofilled again. (not fine!)

Can we please have the component respect the users choice to remove the filter? ([a history](https://github.com/ghDaYuYu/foo_discogs/issues/42) could easily bring back the filter, if needed)

![filter](https://user-images.githubusercontent.com/974980/130308447-e6f69275-88ea-441a-aa1d-333353e9050c.gif)

Thank you :)

**Comment by ghuDaYuYu** [comment]
Could please describe the user case for that scenario, what are you trying to achieve, what is the reason to delete the album title? Do you need to rename the album, suspect that the album spelling might be wrong?

**Comment by frogworth** [comment]
Hi @ghuDaYuYu, this happens to me all the time too.

Not all albums in our collections are named the same as they are in Discogs. This happens a lot with compilations for instance - Vol 2 or Vol. 2 or Volume 2? Sometimes the spine says Volume II and the cover Vol 2!
Or you have a Japanese album and you've put the English translation in the title, but Discogs doesn't have it, or only lists it in English.

Then, if it's Boris say, we might forget that they're Boris (3) and click through a few different Boris results. If we also don't know how the title is styled in Discogs, we want to put in a minimal filter term and then test it on a number of artist results until we find the right combination.

As these are exceptions, we want to enable auto-fill for album titles, but to be able to erase that when it's wrong without the frustration of redoing that as we go.

**Comment by ghuDaYuYu** [comment]
Hi frogworth, 

I think by now, we covered two use cases then,
a ) Minimal filter term: never change its content (fixed in mod.18.2).
b ) Filter is empty: auto fill if available in release list. I believe, but may be wrong, this is the most useful and common scenario.

If I am not wrong a and b are working properly.

Now this new use case, in which, we can not type anything on the filter, because we need to recognize it visually, we don't have a Japanese keyboard...

c ) Filter is empty: we need to visual recognize the title.

So b and c have the same input. In running out of ideas here, either
- A checkbox to activate/disable auto-fill title
- The user enters a single space in the filter to signal that he/she does not want it overridden.

Please, feel free to provide any suggestions if you already have something in mind.

**Comment by frogworth** [comment]
Ah, I see - so currently the plugin does not override the content of the filter unless it is empty.
That works for my use cases generally, then.

I can imagine that under certain circumstances one might want to explore the entire result set for multiple artist matches, and then the autofill would be annoying. Admittedly that's not a use case I had described above.

My expectation would probably be the same as @gitgetgot - "autofill the filter based on album title when the tagging dialog is opened, and then don't change what I enter afterwards, even if it's empty".
In general the current behaviour of the plugin will work just fine for me, but the re-filling of the filter when changing artists does strike me as "wrong", FWIW :)

**Comment by frogworth** [comment]
I mean, here's one use case: I stick a CD in the drive and it has "My CD Album" as the title because whoever mastered it didn't know how to set the CDTEXT.
Now, I realise we can edit the title before tagging, but it feels like that step shouldn't be necessary.

**Comment by ghuDaYuYu** [comment]
Yes, haha, the initial bug you raised was a bloody torture!
You are right, that step should not be necessary.
Well, sigh... for now issue solved 'press space bar in the filter'  🥇

**Comment by frogworth** [comment]
Ahhh well I am sorry!
You're a hero for all the work you've done so far.

Space bar is a fine workaround for now!

**Comment by ghuDaYuYu** [comment]
No.., the medal was ironic. We´ll find a nicer solution in another moment.
Thanks for your help
Regards

**Comment by gitgetgot** [comment]
> 
> 
> Could please describe the user case for that scenario, what are you trying to achieve, what is the reason to delete the album title? Do you need to rename the album, suspect that the album spelling might be wrong?

The usecase is pretty simple:
I want to clear the filter so that I can see ALL releases of a chosen artist.
I don't want to clear the filter every time, I change an artist, to see ALL releases of that artist.

**Comment by ghuDaYuYu** [comment]
Solution has been provided

**Comment by gitgetgot** [comment]
> Solution has been provided

The space-bar one, you wrote?

How would this work?
Sorry, I don't get it.
When I change the Artist, pressing the Space-Bar does nothing.
When I focus the Filter, it just adds a space after the filter-term, which is pretty useless.
I do have to click the x to clear the filter (for each artist change again).

So obviously, I don't understand the provided solution for my usecase and the attached video in my initial post.
Can someone help me out?

frogworth had put it in good words:
> My expectation would probably be the same as @gitgetgot - "autofill the filter based on album title when the tagging dialog is opened, and then _don't change what I enter afterwards_, **even if it's empty**".
> In general the current behaviour of the plugin will work just fine for me, but the re-filling of the filter when changing artists does strike me as "wrong", FWIW :)

**Comment by frogworth** [comment]
@gitgetgot The workaround is to put just a space _in the filter_ - rather than clicking the x to clear it.
This will prevent the filter from being overwritten by whatever is in the Album Title tags for the files you're tagging. You can click through different artists and you'll see all their releases.

@ghuDaYuYu has explained that it's quite difficult to change the plugin's behaviour, so that's the workaround we have for now.
